name: Feature Request
description: Suggest a new feature
title: '[Feature] '
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: 'Have an idea for a new feature? Let us know!'

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the desired feature
      placeholder: 'What would you like to add or improve?'
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Why would this be useful?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: Any ideas on how to implement this?
      placeholder: 'Optional: describe your approach'
